
security:
  oauth2:
    client:
      # 该客户端被分配的id、密码
      client-id: cms
      client-secret: secret
      grant-type: authorization_code
      token-name: access_token
      # 从OAUTH服务端获取授权的地址
      user-authorization-uri: http://auth.bigfb.com:7777/oauth/authorize
      # 从OAUTH服务端获取token的地址
      access-token-uri: http://auth.bigfb.com:7777/oauth/token
    resource:
      # 从OAUTH服务端校验token的地址
      token-info-uri: http://auth.bigfb.com:7777/oauth/check_token
      # 从OAUTH服务端获取用户信息的接口地址
      user-info-uri: http://auth.bigfb.com:7777/user


server:
  port: 7000


spring:
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html